const router = require('express').Router();
const appSettingRouters = require('./appSetting-routers');
const userRouter = require('./user-routes');
const bannerRouters = require('./banner-routes');
const bookingRoutes = require('./booking-routes');
const troubleRouter = require('./trouble-routes');
const authRouters = require('./auth.router');
const chargingStationRoutes = require('./charging-station-routes');
const favoriteStationRoutes = require('./favorite-charger-station-router');
const bankCardRoutes = require('./bank-card-routes');
const chargeConnections = require('./charge-connection');
const vehicleRouters = require('./vehicle.router');
const qrCodeRoutes = require('./qrcode');
const InquiryRouters = require('./Inquiry-routers');
const ReviewRouter = require('./review-router');
const paymethodRouters = require('./paymethod.routes');
const termsRouters = require('./terms-routes');
router.use(bannerRouters);
router.use(userRouter);
router.use(bookingRoutes);
router.use(troubleRouter);
router.use(authRouters);
router.use(chargingStationRoutes);
router.use(favoriteStationRoutes);
router.use(bankCardRoutes);
router.use(chargeConnections);
router.use(vehicleRouters);
router.use(qrCodeRoutes);
router.use(appSettingRouters);
router.use(InquiryRouters);
router.use(ReviewRouter);
router.use(paymethodRouters);
router.use(termsRouters);
module.exports = router;
