version: "3.8"

services:
  db:
    image: mysql:5-oracle
    networks:
      - hdoev
    ports:
      - "${SQL_HOST}:${SQL_PORT}:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${SQL_PASSWORD}
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--host", "127.0.0.1", "--port", "3306", "--user", "root", "--password=${SQL_PASSWORD}"]
      interval: 2s
      retries: 10
    volumes:
      - ../data_backup.sql:/srv/data

  admin:
    image: phpmyadmin:5-apache
    networks:
      - hdoev
    ports:
      - 127.0.0.1:8081:80
    environment:
      - MYSQL_ROOT_PASSWORD=${SQL_PASSWORD}
    depends_on:
      db:
        condition: service_healthy

networks:
  hdoev:
