export enum USER_LOG_STATUS {
  ID_FAIL = 'ID_FAIL',
  PASSWORD_FAIL = 'PASSWORD_FAIL',
  SUCCESS = 'SUCCESS',
  BLOCKED = 'BLOCKED',
  INFO = 'INFO',
  EXCEL_DOWNLOAD = 'EXCEL_DOWNLOAD',
  PRIVATE = 'PRIVATE',
  DELETE = 'DELETE',
  CREATE = 'CREATE',
  UPDATE = 'UPDATE',
  LOGOUT = 'LOGOUT',
  INQUIRY = 'INQUIRY',
}
